### ISSUE TITLE
Organize config files both for the observation space and for the environment

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/curlad#2]

**Comment by DanielCoelho112** [comment]
Done. To set up an experience we have to define 3 config files:

obs_config.yaml

```yaml
speed:
  module: actor_state.speed
gnss:
  module: navigation.gnss
central_rgb:
  module: camera.rgb
  fov: 90
  width: 640
  height: 360
  location: [1.0, 0.0, 1.5]
  rotation: [0.0, 0.0, 0.0]
route_plan:
  module: navigation.waypoint_plan
  steps: 20
control:
  module: actor_state.control
monitor:
  module: camera.rgb
  fov: 90
  width: 640
  height: 360
  location: [1.0, 0.0, 1.5]
  rotation: [0.0, 0.0, 0.0]

```
policy.yaml

```yaml
entry_point: curlad.agents.dummy.dummy_agent:DummyAgent
kwargs:
  throttle: 1
  steer: 0
  brake: 0  
```

train.yaml

```yaml
- env_name: leaderboard_v0.yaml
  description: "First experiment to check if everything works."
  n_episodes: 2
  moving_window: 20
```
